
imie_customer:
    resource: "@IMIECustomerBundle/Controller/"
    type:     annotation
    prefix:   /

imie_admin:
    resource: "@IMIEAdminBundle/Controller/"
    type:     annotation
    prefix:   /

imie_guest:
    resource: '@IMIEGuestBundle/Controller/'
    type: annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation
