imie_customer:
    resource: "@IMIECustomerBundle/Controller/"
    type:     annotation
    prefix:   /

imie_admin:
    resource: "@IMIEAdminBundle/Controller/"
    type:     annotation
    prefix:   /